package pulse.properties;

public enum NumericPropertyKeyword {
	DIFFUSIVITY, THICKNESS, DIAMETER, MAXTEMP, NUMPOINTS, NONLINEAR_PRECISION, PULSE_WIDTH, 
	SPOT_DIAMETER, TIME_LIMIT, GRID_DENSITY, SPECIFIC_HEAT, CONDUCTIVITY, EMISSIVITY,
	DENSITY, ABSORBED_ENERGY, TEST_TEMPERATURE, LINEAR_RESOLUTION, GRADIENT_RESOLUTION,
	BUFFER_SIZE, ERROR_TOLERANCE, PYROMETER_SPOT, BASELINE_SLOPE, BASELINE_INTERCEPT,
	TAU_FACTOR, DETECTOR_GAIN, DETECTOR_IRIS, HEAT_LOSS_FRONT, HEAT_LOSS_SIDE, HEAT_LOSS_REAR,
	HEAT_LOSS, RSQUARED, SUM_OF_SQUARES, ITERATION;	
}
