/**
 * Contains various listeners that deal with events associated with the individual {@code SearchTask}s, 
 * their statuses, logging and result generation, as well as with the task repository events generated by 
 * a {@code TaskManager}.
 */

package pulse.tasks.listeners;